name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/260 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Stash any local changes
      run: git stash
      
    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Config script and save output to file
      run: cd Files && python app.py
      
    - name: Run Warp script and save output to file
      run: cd Files && python warp.py
      
    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py

    - name: Check changes
      run: |
        echo "Checking the changes made..."
        git status
        ls -l Files/
        
    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Updated ⚡️"
        add: "."
        push: "https://github.com/coldwater-10/V2ray-Config.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
